[package]
name = "shunkakinoki"
version = "4.5.1"
authors = ["Shun Kakinoki <shunkakinoki@gmail.com>"]
edition = "2018"
license = "MIT"
homepage = "https://github.com/shunkakinoki/shunkakinoki"
description = "shunkakinoki"
autobins = false
include = ["shunkakinoki/**/*", "Cargo.toml"]

[[bin]]
name = "shunkakinoki"
path = "shunkakinoki/main.rs"

[[test]]
name = "shunkakinoki"
path = "shunkakinoki/tests/main.rs"

[dependencies]
clap = "2.33.0"
self_update = "0.13"
webbrowser = "0.5.2"

[dev-dependencies]
version-sync = "0.8"
