name: Run Markdown Lint
on:
  push:
    branches:
      - master
    paths:
      - "**.md"
  pull_request:
    paths:
      - "**.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@master
        with:
          ruby-version: 2.6

      - name: Set Up Bundler
        run: gem install bundler

      - name: Install with bundle
        run: bundle install

      - name: Lint with Markdown
        run: bundle exec mdl -s style.rb -wg .
