name: Run Markdown Lint
on:
  pull_request:
    paths:
      - "Gemfile"
      - "Gemfile.lock"
      - "**.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@master
        with:
          ruby-version: 2.6
      - name: Cache bundler
        id: cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            gem-
      - name: Install dependencies with bundler
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          gem install bundler
          bundle install --deployment
      - name: Run Markdown Lint
        run: |
          bundle exec mdl -s style.rb -wg .
      - name: Label on PR
        uses: awact/label-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ADD_LABEL: "gha-markdown"
