name: Markdown
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@master
        with:
          ruby-version: '2.x'
      - name: Cache bundler
        id: cache
        uses: actions/cache@v1
        with:
          path: ./vendor/bundle
          key: gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            gem-
      - name: Install dependencies with bundler
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          gem install bundler --no-document
          bundle config path ./vendor/bundle
          bundle install --jobs 4 --retry 3 --deployment
      - name: Run Markdown Lint
        run: |
          bundle exec mdl -s style.rb -wg .
