name: Pull Request Auto Assign
on:
  pull_request:
    types: [opened]
jobs:
  assign:
    name: Assign Author to PR
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/assign-author@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
