name: ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: actions/setup-ruby@master
      with:
        version: 2.6
        
    - name: Set up bundler
      run: gem install bundler

    - name: Install with bundle
      run: bundle install

    - name: Lint with Markdown
      run: bundle exec mdl -s style.rb -wg .