name: Rust
on: pull_request
jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Cache cargo
        id: cache
        uses: actions/cache@v1
        with:
          path: ~/.cargo
          key: rust-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            rust-
      - uses: actions-rs/cargo@v1
      - name: Install rust dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          rustup component add clippy
          cargo update
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
