name: Auto Sync Wiki
on:
  push:
    branches:
      - master
    paths:
      - wiki
jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Upload Release Notes to Wiki
        uses: docker://decathlon/wiki-page-creator-action:latest
        env:
          ACTION_MAIL: shunkakinoki@gmail.com
          ACTION_NAME: shunkakinoki
          GH_PAT: ${{ secrets.GH_PAT }}
          MD_FOLDER: wiki
          OWNER: shunkakinoki
          REPO_NAME: shunkakinoki
